# Generated by Django 3.0.3 on 2020-02-28 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
        ('stands', '0001_initial'),
        ('emotionTypes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emotionTypes.EmotionTypes', verbose_name='emotionID')),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Person', verbose_name='personID')),
                ('standID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stands.Stand', verbose_name='standID')),
            ],
        ),
    ]
