# Generated by Django 3.0.3 on 2020-02-26 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.BooleanField(verbose_name='person')),
                ('emotion', models.BooleanField(verbose_name='emotion')),
                ('age', models.BooleanField(verbose_name='age')),
                ('sex', models.BooleanField(verbose_name='sex')),
                ('people', models.BooleanField(verbose_name='people')),
                ('eventId', models.ForeignKey(max_length=512, on_delete=django.db.models.deletion.CASCADE, to='events.Event', verbose_name='eventId')),
            ],
        ),
    ]
