# Generated by Django 3.0.3 on 2020-02-26 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=512, verbose_name='address')),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Person', verbose_name='personID')),
            ],
        ),
    ]
