# Generated by Django 3.0.3 on 2020-02-28 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emotionTypes', '0001_initial'),
        ('stands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(verbose_name='age')),
                ('sex', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], verbose_name='sex')),
                ('emotionTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emotionTypes.EmotionTypes', verbose_name='emotionID')),
                ('standId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stands.Stand', verbose_name='standID')),
            ],
        ),
    ]
