# Generated by Django 3.0.3 on 2020-02-26 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('stands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(max_length=512, on_delete=django.db.models.deletion.CASCADE, to='users.User', verbose_name='owner')),
                ('standId', models.ForeignKey(max_length=512, on_delete=django.db.models.deletion.CASCADE, to='stands.Stand', verbose_name='stand')),
            ],
        ),
    ]
